server.port: 8080

logging:
  level:
    root: INFO
    com.noodlestar: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 27017
      database: noodlestar
      authentication-database: admin
      auto-index-creation: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5


---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: noodlestar
      username: root
      password: password
      authentication-database: admin

