# version: '3.8'

services:
  noodlestar-frontend:
    image: noodlestar-frontend
    container_name: noodlestar-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
