name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Go Swagger CLI
        run: go install github.com/swaggo/swag/cmd/swag@v1.3.2

      - name: Grant execute perm on cover.sh
        run: chmod +x cover.sh

      # Run backend tests
      - name: Build and test backend
        run: ./gradlew clean build