services:

  noodlestar:
    build: .
    hostname: noodlestar
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - SPRING_DATA_MONGODB_URI=mongodb+srv://doadmin:WQ723ZxOJ81T90I5@db-mongodb-noodlestar-e6ec5c6f.mongo.ondigitalocean.com/admin?retryWrites=true&w=majority
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb

  noodlestarFrontend:
    image: noodlestar-frontend
    container_name: noodlestar-frontend
    build:
      context: ../noodlestar-frontend
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - "3000:3000"
    volumes:
      - ../noodlestar-frontend/src:/app/src


  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  #      healthcheck:
  #        test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
  #        retries: 5
  #        interval: 15s
  #        start_period: 30s

  mongo-express-noodlestar:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8085:8081