@startuml
hide footbox
actor Staff
participant "Noodle Star System" as System


ref over Staff, System : Login.puml

Staff -> System: getAllReservations()
System -> System: retrieveReservationList()
System --> Staff: returnReservations()

' Extend: Deleting a reservation is optional
opt Delete Reservation (optional)
    Staff -> System: deleteReservation(reservationId)
    System -> System: removeReservation(reservationId)
    System --> Staff: confirmReservationCancellation
end opt

@enduml
