name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: NoodleStar/noodlestar-frontend/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./NoodleStar/noodlestar-frontend

      # Step 4: Lint in batches to avoid memory issues
      - name: Run ESLint in batches
        run: |
          npx eslint src/components --ext ts,tsx --cache --report-unused-disable-directives --max-warnings 0
          npx eslint src/utils --ext ts,tsx --cache --report-unused-disable-directives --max-warnings 0
          npx eslint src/pages --ext ts,tsx --cache --report-unused-disable-directives --max-warnings 0
        working-directory: ./NoodleStar/noodlestar-frontend

      # Step 5: Build the project
      - name: Run build to ensure no build errors
        run: npm run build
        working-directory: ./NoodleStar/noodlestar-frontend
