name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies for server
        run: npm install
        working-directory: ./NoodleStar

      # Start Node.js server
      - name: Start Node.js server
        run: |
          node server.js &
          sleep 5 # Wait for the server to start

      # Install Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Build Docker containers
      - name: Build Docker containers
        run: docker-compose -f ./NoodleStar/docker-compose.yml build

      # Start Docker containers
      - name: Start Docker containers
        run: docker-compose -f ./NoodleStar/docker-compose.yml up -d

      # Install dependencies for frontend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./NoodleStar/noodlestar-frontend

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./NoodleStar/noodlestar-frontend

      # Run Playwright tests on Chrome only
      - name: Run Playwright tests on Chrome
        run: npx playwright test ./e2e --project=chromium
        working-directory: ./NoodleStar/noodlestar-frontend

      # Upload Playwright test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./NoodleStar/noodlestar-frontend/playwright-report/
          retention-days: 30

      # Stop and remove Docker containers
      - name: Stop and Remove Docker containers
        run: docker-compose -f ./NoodleStar/docker-compose.yml down

      # Stop Node.js server
      - name: Stop Node.js server
        run: |
          pkill -f server.js || true
